config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show create update] do
    member do
      get :result
      post :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :achievements, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :achievements, dependent: :destroy
  has_many :users, through: :achievements

  enum rule: {
    no_rule: 0,
    all_by_category: 1,
    all_by_difficulty: 2,
    first_attempt_success: 3
  }

  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :img_url, presence: true,
                      format: { with: /\A.+\.(jpe?g|JPE?G|png|PNG)\z/,
                                message: :not_an_image }
end

app/controllers/admin/badges_controller.rb
# frozen_string_literal: true

class Admin::BadgesController < Admin::BaseController
  before_action :set_badge, only: %i[edit update destroy]

  def index
    @badges = Badge.all
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      flash[:success] = t('.create.success')

      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      flash[:success] = t('.update.success')

      redirect_to admin_badges_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy

    flash[:success] = t('.destroy.success')

    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:title, :rule, :sub_rule, :img_url)
  end

  def set_badge
    @badge = Badge.find(params[:id])
  end
end

app/views/admin/badges/_badge.html.erb
<tr class="align-middle">
  <td><%= image_tag badge.img_url, size: '50' %></td>
  <td><%= badge.title %></td>
  <td><%= badge.rule.titleize %></td>
  <td><%= badge.sub_rule %></td>
  <td>
    <%= link_to octicon('pencil', class: 'align-middle'),
                edit_admin_badge_path(badge),
                class: 'btn btn-info'%>
    <%= link_to octicon('trash', class: 'align-middle'),
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: t('.links.confirm') },
                class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with(model: [:admin, @badge], local: true) do |f| %>
  <%= render 'shared/errors', object: f.object %>

  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :rule %>
    <%= f.select :rule,
                 options_for_select(Badge.rules.map { |k, v| [k.titleize, Badge.rules.key(v)] }, @badge.rule),
                 { prompt: true },
                 { class: 'form-select' } %>
  </div>

  <div class="mb-3">
    <%= f.label :sub_rule %>
    <%= f.text_field :sub_rule, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :img_url %>
    <%= f.text_field :img_url, class: 'form-control' %>
  </div>

  <%= f.submit button_text, class: 'btn btn-primary' %>

  <%= link_to t('.links.back'), admin_badges_path, class: 'btn btn-secondary' %>
<% end %>

app/views/admin/badges/edit.html.erb
<h1 class="mb-4">
  <%= t('.header') %>
</h1>

<div class="mb-4">
  <%= image_tag @badge.img_url, size: '50' %>
</div>

<%= render 'form', button_text: t('.buttons.update') %>

app/views/admin/badges/index.html.erb
<h1 class="mb-4">
  <%= t('.header') %>
</h1>

<%= link_to t('.links.create'), new_admin_badge_path, class: 'btn btn-primary mb-3' %>

<div class="table-responsive mt-4">
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th scope="col"><%= t('.table.image') %></th>
        <th scope="col"><%= t('.table.title') %></th>
        <th scope="col"><%= t('.table.rule') %></th>
        <th scope="col"><%= t('.table.sub_rule') %></th>
        <th scope="col"><%= t('.table.actions') %></th>
      </tr>
    </thead>

    <tbody>
      <%= render @badges %>
    </tbody>
  </table>
</div>

app/views/admin/badges/new.html.erb
<h1 class="mb-4">
  <%= t('.header') %>
</h1>

<%= render 'form', button_text: t('.buttons.create') %>