config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show create update] do
    member do
      get :result
      post :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :achievements, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
# frozen_string_literal: true

class TestPassage < ApplicationRecord
  self.table_name = 'tests_users'

  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_current_question, on: :create
  before_update :before_update_set_next_question

  scope :passed, -> { where(passed: true) }

  MINIMAL_SUCCESS_RATE = 85

  def accept!(answer_ids)
    self.correct_questions += 1 if correct_answer?(answer_ids)

    save!
  end

  def completed?
    current_question.nil?
  end

  def pass
    update_column(:passed, true) if passed_by_answers? # rubocop:disable Rails/SkipsModelValidations
  end

  def current_progress
    passed_questions_count = test.questions.order(:id).index(current_question)
    (passed_questions_count.to_f / test.questions.count * 100).round
  end

  def success_rate
    (correct_questions.to_f / test.questions.count * 100).round
  end

  def passed_by_time?
    return true if test.countdown.zero?

    created_at + test.countdown >= Time.zone.now
  end

  private

  def before_validation_set_current_question
    self.current_question = test.questions.first
  end

  def correct_answer?(answer_ids)
    return false unless answer_ids

    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def before_update_set_next_question
    self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
  end

  def passed_by_answers?
    success_rate >= MINIMAL_SUCCESS_RATE
  end
end

app/controllers/test_passages_controller.rb
# frozen_string_literal: true

class TestPassagesController < ApplicationController
  before_action :find_test_passage!, only: %i[show update result gist]
  before_action :find_test!, only: %i[show update result]

  def show
    @endtime = @test_passage.created_at + @test_passage.test.countdown
  end

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed? || !@test_passage.passed_by_time?
      @test_passage.pass

      if @test_passage.passed?
        AchievementService.new(@test_passage).call
        TestsMailer.completed_test(@test_passage).deliver_now
      end

      redirect_to result_test_passage_path(@test_passage)
    else
      @endtime = @test_passage.created_at + @test_passage.test.countdown

      render :show
    end
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

  def result; end

  def gist
    client = Octokit::Client.new(access_token: ENV.fetch('GITHUB_ACCESS_TOKEN', nil))
    service = GistQuestionService.new(@test_passage.current_question, client)
    result = service.call
    gist_url = result.html_url

    flash_options = service.success? ? { notice: t('.success', link: gist_url) } : { danger: t('.failed') }

    save_gist(gist_url)

    redirect_to @test_passage, flash_options
  end

  private

  def find_test_passage!
    @test_passage = TestPassage.find(params[:id])
  end

  def find_test!
    @test = @test_passage.test
  end

  def save_gist(gist_url)
    @test_passage.current_question.gists.create(
      user_id: @test_passage.user.id,
      url: gist_url
    )
  end
end

app/helpers/test_passage_helper.rb
# frozen_string_literal: true

module TestPassageHelper
  def current_question_number(question)
    question.test.questions.order(:id).index(question) + 1
  end

  def timer(endtime)
    tag.div(id: 'countdown',
            class: 'row justify-content-center border rounded-pill mb-4',
            data: { endtime: })
  end
end

app/views/test_passages/result.html.erb
<h1 class="mb-4">
  <%= t('.header', title: @test.title) %>
</h1>

<h4 class="mb-4">
  <%= t('.corrects', correct_questions: @test_passage.correct_questions,
                     questions_count: @test.questions.count) %>
  <span class="badge <%= @test_passage.passed? ? 'bg-success' : 'bg-danger' %>">
    <%= @test_passage.success_rate %>%
  </span>
</h4>

<% if @test_passage.passed? %>
  <div class="alert alert-success">
    <%= t('.success') %>
  </div>
<% else %>
  <div class="alert alert-danger">
    <%= t('.failed') %>
  </div>
<% end %>

<%= link_to t('.links.back'), tests_path, class: 'btn btn-secondary' %>

app/views/test_passages/show.html.erb
<h1 class="mb-4">
  <%= t('.header', title: @test.title) %>
</h1>

<div class="progress mb-4">
  <div
      class="progress-bar bg-primary" role="progressbar"
      style="width: <%= @test_passage.current_progress %>%"
      aria-valuenow="<%= @test_passage.current_progress %>"
      aria-valuemin="0" aria-valuemax="100">
  </div>
</div>

<%= timer(@endtime.to_s) if @test_passage.test.countdown > 0 %>

<h3 class="mb-4">
  (<%= current_question_number(@test_passage.current_question)%> / <%= @test.questions.count %>)
  <%= @test_passage.current_question.body %>
</h3>

<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |f| %>
  <%= f.collection_check_boxes :answer_ids,
                               @test_passage.current_question.answers,
                               :id,
                               :body,
                               include_hidden: false do |b| %>
    <div class="mb-3 row">
      <div class="form-check">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    </div>
  <% end %>

  <%= f.submit t('.buttons.submit'), id: 'next-question', class: 'btn btn-primary' %>

  <%= link_to t('.links.gist'), gist_test_passage_path(@test_passage), method: :post, class: 'btn btn-warning' %>
<% end %>