config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show create update] do
    member do
      get :result
      post :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :achievements, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/views/shared/_errors.html.erb
<% if object.present? && object.errors.any? %>
  <%= content_tag :div, id: 'error_explanation', class: 'object-errors', data: { object_id: object.id } do %>
    <div class="alert alert-danger">
      <%= t('.message', count: object.errors.count) %>.
    </div>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_menu.html.erb
<header class="navbar navbar-fixed-top p-3 bg-dark">
  <div class="container">
    <%= link_to t('.links.home'), root_path, class: 'navbar-brand mb-0 h1 text-white' %>

    <ul class="nav col-12 col-lg-auto">
      <% if current_user&.admin? %>
        <li class="nav-link px-2 text-white"><%= "\u2699 #{t('.admin')}:" %></li>
        <li><%= link_to t('.links.admin.tests'), admin_tests_path, class: 'nav-link px-2 text-white' %></li>
        <li><%= link_to t('.links.admin.badges'), admin_badges_path, class: 'nav-link px-2 text-white' %></li>
      <% end %>
    </ul>

    <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <ul class="nav col-12 col-lg-auto mb-md-0">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-link px-2 text-white" data-bs-toggle="dropdown">
              <%= t('.greeting', name: current_user.first_name.capitalize) %> <b class="caret"></b>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to t('.links.achievements'), achievements_path, class: 'dropdown-item' %></li>
              <li class="dropdown-divider"></li>
              <li><%= link_to t('.links.logout'), destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t('.links.signup'), new_user_registration_path, class: 'nav-link px-2 text-white' %></li>
          <li><%= link_to t('.links.login'), new_user_session_path, class: 'nav-link px-2 text-white' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>