config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show create update] do
    member do
      get :result
      post :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :achievements, only: :index

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index

    resources :badges, except: :show
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  ANSWERS_LIMIT_FOR_QUESTION = 4

  validates :body, presence: true
  validate :validate_count

  scope :correct, -> { where(correct: true) }

  private

  def validate_count
    return unless question.answers.count == ANSWERS_LIMIT_FOR_QUESTION

    errors.add(:base, type: :too_much, message: I18n.t('activerecord.errors.models.answer.attributes.base.too_much'))
  end
end

app/controllers/admin/answers_controller.rb
# frozen_string_literal: true

class Admin::AnswersController < Admin::BaseController
  before_action :find_answer!, except: %i[new create]
  before_action :find_question!, only: %i[new create]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      flash[:success] = t('.create.success')

      redirect_to admin_question_path(@question)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @answer.update(answer_params)
      flash[:success] = t('.update.success')

      redirect_to admin_answer_path(@answer)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy

    flash[:success] = t('.destroy.success')

    redirect_to admin_question_path(@answer.question)
  end

  private

  def find_answer!
    @answer = Answer.find(params[:id])
  end

  def find_question!
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :find_answer!, except: %i[new create]
  before_action :find_question!, only: %i[new create]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      redirect_to @question
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @answer.update(answer_params)
      redirect_to @answer
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy

    redirect_to @answer.question
  end

  private

  def find_answer!
    @answer = Answer.find(params[:id])
  end

  def find_question!
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/views/admin/answers/_answer.html.erb
<li class="list-group-item">
  <b>
    <%= answer.body %>
  </b>

  <br/>

  <%= link_to t('.links.show'), admin_answer_path(answer), class: 'btn btn-sm btn-dark' %>
  <%= link_to t('.links.edit'), edit_admin_answer_path(answer), class: 'btn btn-sm btn-info' %>
  <%= link_to t('.links.destroy'),
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: t('.links.confirm') },
              class: 'btn btn-sm btn-danger' %>
</li>

app/views/admin/answers/_form.html.erb
<h2 class="mb-4">
  <%= @answer.question.body %>
</h2>

<%= form_with(model: [:admin, @question, @answer], local: true) do |f| %>
  <%= render 'shared/errors', object: f.object %>

  <div class="mb-3">
    <%= f.label :body %>
    <%= f.text_area :body, size: '50x5', class: 'form-control' %>
  </div>

  <div class="mb-3">
    <div class="form-check">
      <%= f.check_box :correct %>
      <%= f.label :correct %>
    </div>
  </div>

  <%= f.submit button_text, class: 'btn btn-primary' %>

  <%= link_to t('.links.back'), admin_question_path(@answer.question), class: 'btn btn-secondary' %>
<% end %>

app/views/admin/answers/edit.html.erb
<h1 class="mb-4">
  <%= t('.header') %>
</h1>

<%= render 'form', button_text: t('.buttons.update') %>

app/views/admin/answers/show.html.erb
<h1 class="mb-4">
  <%= t('.question') %>: <%= @answer.question.body %>
</h1>

<div class="mb-4">
  <b><%= t('.answer') %></b>: <%= @answer.body %>
</div>

<div class="mb-4">
  <b><%= t('.correct') %></b>: <%= @answer.correct%>
</div>

<%= link_to t('.links.back'), admin_question_path(@answer.question), class: 'btn btn-secondary' %>